# -*- coding: utf-8 -*-
"""preprocess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zmn9vhf2Vhi3zeA5Nhn1CjB5Maa2nfBC
"""


import pandas as pd
from konlpy.tag import Okt
import re

df = pd.read_csv('./crawling/reviews_2020.csv', index_col=0)
print(df.head())

okt = Okt()

stopwords = pd.read_csv('./crawling/stopwords.csv',
                        index_col=0)
movie_stopwords = ['영화', '배우', '감독', '관객', '작품', '주인공', '개봉', '촬영']
stopwords_list = list(stopwords.stopword) + movie_stopwords

count = 0
cleaned_sentences = []
for sentence in df.reviews:
    count += 1
    if count % 10 == 0:
        print('.', end='')
    if count % 100 == 0:
        print('')
    sentence = re.sub('[^가-힣 ]', '', sentence)
    token = okt.pos(sentence, stem=True)
    df_token = pd.DataFrame(token, columns=['word', 'class'])
    df_cleaned_token = df_token[(df_token['class'] == 'Noun') | 
                            (df_token['class'] == 'Verb') |
                            (df_token['class'] == 'Adjective')]
    words = []
    for word in df_cleaned_token['word']:
        if len(word) > 1:
            if word not in stopwords_list:
                words.append(word)
    cleaned_sentence = ' '.join(words)
    cleaned_sentences.append(cleaned_sentence)
df['cleaned_sentences'] = cleaned_sentences
print(df.head())

print(df.info())

df = df[['titles', 'cleaned_sentences']]
print(df.info())
df.to_csv('./crawling/cleaned_review_2020.csv')